---
  ec2_instance:
    region: "us-east-1"
    profile: "felipe.guerra"
    key_name: "key-us-east-1-mlg-a-admin-01"
    instance_type: "t2.large"
    image: "ami-0b33d91d"
    wait: "yes"
    zone: "us-east-1a"
    vpc_subnet_id: subnet-8ac911a7
    assign_public_ip: no
    termination_protection: yes
    monitoring: yes
    group: ['PricingHML-SgpUsEast1DefaultBastion-14ELRB9OKERDQ']
    instance_tags:
      'Name': 'srv-lx-sa-east-1a-mlg-a-admin-01'
      'Created-by': 'felipe'
      'Role': 'admin'
      'SchedulePoweroff': 'nao'
      'Team': 'ti_comercial'
      'Area': 'comercial'
      'Env': 'prd'
      'Project': 'admin'
    volumes:
    - device_name: /dev/sdb
      volume_type: gp2 #http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html
      volume_size: 150
      delete_on_termination: true
    wait_timeout: 300
